version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: imageapp-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jana
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: imageapp
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: